hometask55/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from papermodels.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", main, name='main'),
    path("projects/", include('papermodels.urls')),
    path("contacts/", contacts, name='contacts'),
    path("login/", LoginUser.as_view(), name='login'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

papermodels/urls.py
from django.urls import path
from .views import *

app_name = 'papermodels'

urlpatterns = [
    path('', projects, name='projects'),
    path('<int:model_id>/', project, name='project'),
    path('upload/', upload, name='upload'),
    path('register/', RegisterUser.as_view(), name='register'),
    # path("login/", LoginUser.as_view(), name='login'),
    path("logout/", logout_user, name="logout"),
]

papermodels/models.py
from django.db import models


class PaperModelsCategories(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='papermodels/images')

    def __str__(self):
        return self.title


class PaperModels(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='papermodels/images')
    upload = models.FileField(upload_to='papermodels/uploads')
    category = models.ForeignKey(PaperModelsCategories, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Contacts(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

papermodels/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import *


class AddPostForm(forms.ModelForm):
    class Meta:
        model = PaperModels
        fields = ['title', 'description', 'image', 'upload', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'description': forms.Textarea(attrs={'cols': 50, 'rows': 15}),
        }


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-input'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.TextInput(attrs={'class': 'form-input'}),

        }


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

papermodels/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.http import HttpResponse

from .forms import AddPostForm, RegisterUserForm, LoginUserForm
from .models import *
from django.contrib import messages


def main(request):
    return render(request, 'papermodels/main.html')


def projects(request):
    projects = PaperModelsCategories.objects.all()
    return render(request, 'papermodels/projects.html', {"projects": projects})


def project(request, model_id):
    category_title = get_object_or_404(PaperModelsCategories, pk=model_id).title
    project = PaperModels.objects.filter(category_id=model_id)
    context = {"project": project,
               "id": model_id,
               "cat_title": category_title}
    return render(request, 'papermodels/project.html', context=context)


def upload(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = AddPostForm()
    return render(request, 'papermodels/upload.html', {'form': form})


def contacts(request):
    conts = Contacts.objects.all()
    return render(request, 'papermodels/contacts.html', {'contacts': conts})


def logout_user(request):
    logout(request)
    return redirect('login')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'papermodels/register.html'
    success_url = reverse_lazy('login')  # возвращаемся на форму в случае успеха


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'papermodels/login.html'

    def get_success_url(self):
        return reverse_lazy('login')  # возвращаемся на форму в случае успеха

papermodels/templates/papermodels/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type='image/x-icon' href="{% static 'papermodels/favicon.ico' %}">
</head>
<body>
<div class="container">
<div class="menu">
    <div class="wrap">
        <ul class="menu">
            <li ><a href="{% url 'main' %}"><img class="logo" src="{% static 'papermodels/logo.png' %}" alt="logo"></a></li>
            <li class="text"><a href="{% url 'main' %}">Главная</a></li>
            <li class="text"><a href="{% url 'papermodels:projects' %}">Категории моделей</a></li>
            <li class="text"><a href="{% url 'contacts' %}">Контакты</a></li>
            {% if request.user.is_authenticated %}
            <li class="text last">{{ user.username }} | <a href="{% url 'papermodels:logout' %}">Выйти</a></li>
            {% else %}
            <li class="text last"><a href="{% url 'papermodels:register' %}">Регистрация</a> | <a href="{% url 'login' %}">Авторизация</a></li>
            {% endif %}
        </ul>

    </div>
</div>
<h1 class="title">МОДЕЛИ ИЗ БУМАГИ</h1>
<div class="content">
    <div class="wrap">
        {% block content %}
        {% endblock %}
    </div>
</div>
</div>
</body>
</html>

papermodels/templates/papermodels/contacts.html
{% extends 'papermodels/base.html' %}
{% load static %}
{% block content %}
<h2 class="cat_title">На любые ваши вопросы с удовольствием ответят члены нашей команды:<br></h2>
<div class="models contacts">
    {% for cont in contacts %}
    <div class="elements">
        <h3 class="top"><a href="{{ cont.url }}" target="_blank">{{ cont.title }}</a></h3>
        <div class="blog_text"><p>{{ cont.description | striptags | truncatechars:800 }}</p></div>
    </div>
    {% endfor %}
</div>
{% endblock %}

papermodels/templates/papermodels/login.html
{% extends 'papermodels/base.html' %}
{% load static %}
{% block content %}
<h2 class="cat_title">-*Авторизация*-</h2>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label  class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>{{ f }}</p>
    <div class="form-error">{{f.errors}}</div>
    {% endfor %}
    <button class="btn" type="submit">Авторизация</button>
</form>

{% endblock %}

papermodels/templates/papermodels/main.html
{% extends 'papermodels/base.html' %}
{% load static %}
{% block content %}
<div class="content start">
    Вашему вниманию представлен сборник великолепных моделей из бумаги с инструкциями по сборке и лекала.<br>
    Модели разделены по категориям, рассчитаны на самый широкий круг увлеченных людей.<br>
    Создавайте прекрасные города, зоопарки, морские флотилии, аэродромы и железные дороги. Cами и вместе с детьми.
</div>
<footer class="footer">
    <a href="{% url 'papermodels:projects' %}">
    <img class="back_img" src="{% static 'papermodels/models.png' %}" alt="backimage" ></div>
    </a>
</footer>
{% endblock %}

papermodels/templates/papermodels/project.html
{% extends 'papermodels/base.html' %}
{% load static %}
{% block content %}
{% if id == 1 %}
<link rel="stylesheet" href="{% static 'css/style_prj1.css' %}">
{% elif id == 2 %}
<link rel="stylesheet" href="{% static 'css/style_prj2.css' %}">
{% elif id == 3 %}
<link rel="stylesheet" href="{% static 'css/style_prj3.css' %}">
{% endif %}

<h2 class="cat_title">{{ cat_title }}.<br></h2>
<h4>Моделей: {{ project.count }} <a class="add_model" href="{% url 'papermodels:upload'%}"> + Добавить модель</a>
    {% if request.user.is_authenticated %}
    <em class="last">Нажмите на выбранную модель чтобы загрузить инструкцию</em>
    {% else %}
    <em class="last">Необходимо зарегистрироваться и авторизоваться для загрузки моделей</em>
    {% endif %}
</h4>
<div class="models">
    {% for model in project %}
    <div class="elements">
        {% if request.user.is_authenticated %}
        <h2 class="top"><a href="{{ model.upload.url }}" target="_blank">{{ model.title }}</a></h2>
        <a href="{{ model.upload.url }}" target="_blank"><img class="model_img" src="{{ model.image.url }}"
                                                              alt="img"></a>
        {% else %}
        <h2 class="top"><a href="">{{ model.title }}</a></h2>
        <a href=""><img class="model_img" src="{{ model.image.url }}" alt="img"></a>
        {% endif %}

        <div class="blog_text"><p>{{ model.description | striptags | truncatechars:18 }}</p></div>
    </div>
    {% endfor %}
</div>
<div class="footer"></div>
{% endblock %}

papermodels/templates/papermodels/projects.html
{% extends 'papermodels/base.html' %}
{% load static %}
{% block content %}
<h1 class="projects">*-КАТЕГОРИИ БУМАЖНЫХ МОДЕЛЕЙ-*</h1>
<div class="categories">
    {% for proj in projects %}
    <div class="element">
        <p class="proj_number">{{ proj.id }}</p>
        <a href="{% url 'papermodels:project' proj.id %}"><img class="categories_img" src="{{ proj.image.url }}" alt="img"></a>
        <div class="text_part">
            <p class="modellist"><a href="{% url 'papermodels:project' proj.id %}" class="modellink"> *- {{ proj.title }} -* </a></p>
            <p class="descripion">{{ proj.description | safe }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

papermodels/templates/papermodels/register.html
{% extends 'papermodels/base.html' %}

{% block content %}
<h3>Регистрация</h3>
<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p><label  class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>{{ f }}</p>
    <div class="form-error">{{f.errors}}</div>
    {% endfor %}
    <button class="btn" type="submit">Регистрация</button>
</form>
{% endblock %}

papermodels/templates/papermodels/upload.html
{% extends 'papermodels/base.html' %}

{% block content %}
<h3>Добавление модели</h3>
<form action="{% url 'papermodels:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}:</label>{{ f }}</p>
    <div class="form-error">{{f.errors}}</div>
    {% endfor %}

    <button class="btn" type="submit">Добавить</button>
</form>
{% endblock %}